<?php
/**
 * @file
 * Update file for Token Content Access module.
 */

/**
 * Add config for flood control.
 */
function tca_update_1100() {
  tca_install_add_default_config();
}

/**
 * Add config for flood control.
 */
function tca_install_add_default_config() {
  // Create the config item.
  $config = config('tca.settings');

  // Define the default settings.
  $settings = array(
    'flood_control_active' => TRUE,
    'flood_ip_limit' => 50,
    'flood_ip_window' => 3600,
    'flood_entity_limit' => 5,
    'flood_entity_window' => 21600,
    'flood_control_silent' => FALSE,
    'default_parameter_key' => 'tca',
  );
  $config->setMultiple($settings);
  // Save the config.
  $config->save();
}

/**
 * Upgrade from Drupal 7 to Backdrop CMS.
 */
function tca_update_1000() {
  tca_install_add_default_config();
}
