<?php
/**
 * @file
 * Update file for Token Content Access nodes module.
 */

/**
 * Implements hook_uninstall().
 */
function tca_node_uninstall() {
  $table = 'node';
  $fields = array(
    'tca_active',
    'tca_token',
  );
  foreach ($fields as $field) {
    if (db_field_exists($table, $field)) {
      db_drop_field($table, $field);
    }
  }
}

/**
 * Convert config from flat array to nested array to support more settings per
 * content type
 */
function tca_node_update_1100() {
  // Retrieve the existing config.
  $config = config('tca_node.settings');
  $original_config = $config->get();

  // For each node type, add the existing active setting to an array with a
  // FALSE setting for 'forced' - the new functionality - and set the config.
  foreach ($original_config as $node_type => $active) {
    $new_config = array(
      'active' => $active,
      'forced' => FALSE,
      'override' => FALSE,
      'parameter_key' => config_get('tca.settings', 'default_parameter_key'),
    );
    $config->set($node_type, $new_config);
  }

  // Save the config.
  $config->save();
}

/**
 * Upgrade from Drupal 7 to Backdrop CMS.
 */
function tca_node_update_1000() {
  $node_types = node_type_get_names();
  $config = config('tca_node.settings');
  foreach ($node_types as $name => $label) {
    $config->set($name, update_variable_get('tca_node_active_' . $name, 0));
    update_variable_del('tca_node_active_' . $name);
  }
  $config->save();
}
